#!/bin/bash
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode bclone --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=cartpole,num_trajs=10,run=6.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode bclone --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --max_iter 1001 --bclone_eval_freq 100 --sim_batch_size 1 --log imitation_runs/classic/checkpoints/alg=bclone,task=mountaincar,num_trajs=10,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=cartpole,num_trajs=10,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=ga,task=mountaincar,num_trajs=10,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=cartpole,num_trajs=10,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type l2ball --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=fem,task=mountaincar,num_trajs=10,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 1 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 4 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 7 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode ga --env CartPole-v0 --data imitation_runs/classic/trajs/trajs_cartpole.h5 --limit_trajs 10 --data_subsamp_freq 10 --favor_zero_expert_reward 0 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=cartpole,num_trajs=10,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=1,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=1,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=1,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=1,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=1,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=1,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 1 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=1,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=4,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=4,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=4,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=4,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=4,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=4,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 4 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=4,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=7,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=7,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=7,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=7,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=7,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=7,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 7 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=7,run=6.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=10,run=0.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=10,run=1.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=10,run=2.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=10,run=3.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=10,run=4.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=10,run=5.h5
python scripts/imitate_mj.py --mode ga --env MountainCar-v0 --data imitation_runs/classic/trajs/trajs_mountaincar.h5 --limit_trajs 10 --data_subsamp_freq 5 --favor_zero_expert_reward 1 --min_total_sa 5000 --max_iter 301 --sim_batch_size 1 --reward_type simplex --reward_include_time 0 --log imitation_runs/classic/checkpoints/alg=simplex,task=mountaincar,num_trajs=10,run=6.h5
# # END
# cmd=$(echo "$COMMANDS" | awk "NR == $PBS_ARRAYID")
# echo $cmd

# read -r -d '' OUTPUTFILES << END
# logs_im_classic_2022-08-08_05:21:24/0001_alg=bclone,task=cartpole,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0002_alg=bclone,task=cartpole,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0003_alg=bclone,task=cartpole,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0004_alg=bclone,task=cartpole,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0005_alg=bclone,task=cartpole,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0006_alg=bclone,task=cartpole,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0007_alg=bclone,task=cartpole,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0008_alg=bclone,task=cartpole,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0009_alg=bclone,task=cartpole,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0010_alg=bclone,task=cartpole,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0011_alg=bclone,task=cartpole,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0012_alg=bclone,task=cartpole,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0013_alg=bclone,task=cartpole,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0014_alg=bclone,task=cartpole,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0015_alg=bclone,task=cartpole,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0016_alg=bclone,task=cartpole,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0017_alg=bclone,task=cartpole,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0018_alg=bclone,task=cartpole,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0019_alg=bclone,task=cartpole,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0020_alg=bclone,task=cartpole,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0021_alg=bclone,task=cartpole,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0022_alg=bclone,task=cartpole,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0023_alg=bclone,task=cartpole,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0024_alg=bclone,task=cartpole,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0025_alg=bclone,task=cartpole,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0026_alg=bclone,task=cartpole,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0027_alg=bclone,task=cartpole,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0028_alg=bclone,task=cartpole,num_trajs=10,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0029_alg=bclone,task=mountaincar,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0030_alg=bclone,task=mountaincar,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0031_alg=bclone,task=mountaincar,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0032_alg=bclone,task=mountaincar,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0033_alg=bclone,task=mountaincar,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0034_alg=bclone,task=mountaincar,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0035_alg=bclone,task=mountaincar,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0036_alg=bclone,task=mountaincar,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0037_alg=bclone,task=mountaincar,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0038_alg=bclone,task=mountaincar,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0039_alg=bclone,task=mountaincar,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0040_alg=bclone,task=mountaincar,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0041_alg=bclone,task=mountaincar,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0042_alg=bclone,task=mountaincar,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0043_alg=bclone,task=mountaincar,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0044_alg=bclone,task=mountaincar,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0045_alg=bclone,task=mountaincar,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0046_alg=bclone,task=mountaincar,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0047_alg=bclone,task=mountaincar,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0048_alg=bclone,task=mountaincar,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0049_alg=bclone,task=mountaincar,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0050_alg=bclone,task=mountaincar,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0051_alg=bclone,task=mountaincar,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0052_alg=bclone,task=mountaincar,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0053_alg=bclone,task=mountaincar,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0054_alg=bclone,task=mountaincar,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0055_alg=bclone,task=mountaincar,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0056_alg=bclone,task=mountaincar,num_trajs=10,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0057_alg=ga,task=cartpole,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0058_alg=ga,task=cartpole,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0059_alg=ga,task=cartpole,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0060_alg=ga,task=cartpole,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0061_alg=ga,task=cartpole,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0062_alg=ga,task=cartpole,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0063_alg=ga,task=cartpole,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0064_alg=ga,task=cartpole,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0065_alg=ga,task=cartpole,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0066_alg=ga,task=cartpole,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0067_alg=ga,task=cartpole,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0068_alg=ga,task=cartpole,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0069_alg=ga,task=cartpole,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0070_alg=ga,task=cartpole,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0071_alg=ga,task=cartpole,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0072_alg=ga,task=cartpole,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0073_alg=ga,task=cartpole,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0074_alg=ga,task=cartpole,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0075_alg=ga,task=cartpole,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0076_alg=ga,task=cartpole,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0077_alg=ga,task=cartpole,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0078_alg=ga,task=cartpole,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0079_alg=ga,task=cartpole,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0080_alg=ga,task=cartpole,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0081_alg=ga,task=cartpole,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0082_alg=ga,task=cartpole,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0083_alg=ga,task=cartpole,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0084_alg=ga,task=cartpole,num_trajs=10,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0085_alg=ga,task=mountaincar,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0086_alg=ga,task=mountaincar,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0087_alg=ga,task=mountaincar,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0088_alg=ga,task=mountaincar,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0089_alg=ga,task=mountaincar,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0090_alg=ga,task=mountaincar,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0091_alg=ga,task=mountaincar,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0092_alg=ga,task=mountaincar,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0093_alg=ga,task=mountaincar,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0094_alg=ga,task=mountaincar,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0095_alg=ga,task=mountaincar,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0096_alg=ga,task=mountaincar,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0097_alg=ga,task=mountaincar,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0098_alg=ga,task=mountaincar,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0099_alg=ga,task=mountaincar,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0100_alg=ga,task=mountaincar,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0101_alg=ga,task=mountaincar,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0102_alg=ga,task=mountaincar,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0103_alg=ga,task=mountaincar,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0104_alg=ga,task=mountaincar,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0105_alg=ga,task=mountaincar,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0106_alg=ga,task=mountaincar,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0107_alg=ga,task=mountaincar,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0108_alg=ga,task=mountaincar,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0109_alg=ga,task=mountaincar,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0110_alg=ga,task=mountaincar,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0111_alg=ga,task=mountaincar,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0112_alg=ga,task=mountaincar,num_trajs=10,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0113_alg=fem,task=cartpole,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0114_alg=fem,task=cartpole,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0115_alg=fem,task=cartpole,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0116_alg=fem,task=cartpole,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0117_alg=fem,task=cartpole,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0118_alg=fem,task=cartpole,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0119_alg=fem,task=cartpole,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0120_alg=fem,task=cartpole,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0121_alg=fem,task=cartpole,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0122_alg=fem,task=cartpole,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0123_alg=fem,task=cartpole,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0124_alg=fem,task=cartpole,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0125_alg=fem,task=cartpole,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0126_alg=fem,task=cartpole,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0127_alg=fem,task=cartpole,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0128_alg=fem,task=cartpole,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0129_alg=fem,task=cartpole,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0130_alg=fem,task=cartpole,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0131_alg=fem,task=cartpole,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0132_alg=fem,task=cartpole,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0133_alg=fem,task=cartpole,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0134_alg=fem,task=cartpole,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0135_alg=fem,task=cartpole,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0136_alg=fem,task=cartpole,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0137_alg=fem,task=cartpole,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0138_alg=fem,task=cartpole,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0139_alg=fem,task=cartpole,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0140_alg=fem,task=cartpole,num_trajs=10,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0141_alg=fem,task=mountaincar,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0142_alg=fem,task=mountaincar,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0143_alg=fem,task=mountaincar,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0144_alg=fem,task=mountaincar,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0145_alg=fem,task=mountaincar,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0146_alg=fem,task=mountaincar,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0147_alg=fem,task=mountaincar,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0148_alg=fem,task=mountaincar,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0149_alg=fem,task=mountaincar,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0150_alg=fem,task=mountaincar,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0151_alg=fem,task=mountaincar,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0152_alg=fem,task=mountaincar,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0153_alg=fem,task=mountaincar,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0154_alg=fem,task=mountaincar,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0155_alg=fem,task=mountaincar,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0156_alg=fem,task=mountaincar,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0157_alg=fem,task=mountaincar,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0158_alg=fem,task=mountaincar,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0159_alg=fem,task=mountaincar,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0160_alg=fem,task=mountaincar,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0161_alg=fem,task=mountaincar,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0162_alg=fem,task=mountaincar,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0163_alg=fem,task=mountaincar,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0164_alg=fem,task=mountaincar,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0165_alg=fem,task=mountaincar,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0166_alg=fem,task=mountaincar,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0167_alg=fem,task=mountaincar,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0168_alg=fem,task=mountaincar,num_trajs=10,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0169_alg=simplex,task=cartpole,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0170_alg=simplex,task=cartpole,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0171_alg=simplex,task=cartpole,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0172_alg=simplex,task=cartpole,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0173_alg=simplex,task=cartpole,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0174_alg=simplex,task=cartpole,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0175_alg=simplex,task=cartpole,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0176_alg=simplex,task=cartpole,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0177_alg=simplex,task=cartpole,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0178_alg=simplex,task=cartpole,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0179_alg=simplex,task=cartpole,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0180_alg=simplex,task=cartpole,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0181_alg=simplex,task=cartpole,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0182_alg=simplex,task=cartpole,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0183_alg=simplex,task=cartpole,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0184_alg=simplex,task=cartpole,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0185_alg=simplex,task=cartpole,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0186_alg=simplex,task=cartpole,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0187_alg=simplex,task=cartpole,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0188_alg=simplex,task=cartpole,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0189_alg=simplex,task=cartpole,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0190_alg=simplex,task=cartpole,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0191_alg=simplex,task=cartpole,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0192_alg=simplex,task=cartpole,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0193_alg=simplex,task=cartpole,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0194_alg=simplex,task=cartpole,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0195_alg=simplex,task=cartpole,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0196_alg=simplex,task=cartpole,num_trajs=10,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0197_alg=simplex,task=mountaincar,num_trajs=1,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0198_alg=simplex,task=mountaincar,num_trajs=1,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0199_alg=simplex,task=mountaincar,num_trajs=1,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0200_alg=simplex,task=mountaincar,num_trajs=1,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0201_alg=simplex,task=mountaincar,num_trajs=1,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0202_alg=simplex,task=mountaincar,num_trajs=1,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0203_alg=simplex,task=mountaincar,num_trajs=1,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0204_alg=simplex,task=mountaincar,num_trajs=4,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0205_alg=simplex,task=mountaincar,num_trajs=4,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0206_alg=simplex,task=mountaincar,num_trajs=4,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0207_alg=simplex,task=mountaincar,num_trajs=4,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0208_alg=simplex,task=mountaincar,num_trajs=4,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0209_alg=simplex,task=mountaincar,num_trajs=4,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0210_alg=simplex,task=mountaincar,num_trajs=4,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0211_alg=simplex,task=mountaincar,num_trajs=7,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0212_alg=simplex,task=mountaincar,num_trajs=7,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0213_alg=simplex,task=mountaincar,num_trajs=7,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0214_alg=simplex,task=mountaincar,num_trajs=7,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0215_alg=simplex,task=mountaincar,num_trajs=7,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0216_alg=simplex,task=mountaincar,num_trajs=7,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0217_alg=simplex,task=mountaincar,num_trajs=7,run=6.txt
# logs_im_classic_2022-08-08_05:21:24/0218_alg=simplex,task=mountaincar,num_trajs=10,run=0.txt
# logs_im_classic_2022-08-08_05:21:24/0219_alg=simplex,task=mountaincar,num_trajs=10,run=1.txt
# logs_im_classic_2022-08-08_05:21:24/0220_alg=simplex,task=mountaincar,num_trajs=10,run=2.txt
# logs_im_classic_2022-08-08_05:21:24/0221_alg=simplex,task=mountaincar,num_trajs=10,run=3.txt
# logs_im_classic_2022-08-08_05:21:24/0222_alg=simplex,task=mountaincar,num_trajs=10,run=4.txt
# logs_im_classic_2022-08-08_05:21:24/0223_alg=simplex,task=mountaincar,num_trajs=10,run=5.txt
# logs_im_classic_2022-08-08_05:21:24/0224_alg=simplex,task=mountaincar,num_trajs=10,run=6.txt
# END
# outputfile=$PBS_O_WORKDIR/$(echo "$OUTPUTFILES" | awk "NR == $PBS_ARRAYID")
# echo $outputfile
# # Make sure output directory exists
# mkdir -p "`dirname "$outputfile"`" 2>/dev/null

# cd $PBS_O_WORKDIR

# echo $cmd >$outputfile
# eval $cmd >>$outputfile 2>&1
